/*Desafio: complementando o relatório*/
SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME, TABELA_DE_CLIENTES.VOLUME_DE_COMPRA, TOTAL_VENDA.MES_ANO, TOTAL_VENDA.QUANTIDADE_TOTAL, 
	(CASE WHEN  TABELA_DE_CLIENTES.VOLUME_DE_COMPRA >= TOTAL_VENDA.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS' ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO, ROUND((1 - (TABELA_DE_CLIENTES.VOLUME_DE_COMPRA/TOTAL_VENDA.QUANTIDADE_TOTAL)) * 100, 2) AS PERCENTUAL
		FROM TABELA_DE_CLIENTES INNER JOIN (SELECT NOTAS_FISCAIS.CPF, CONVERT(VARCHAR(7), NOTAS_FISCAIS.DATA_VENDA, 120) AS MES_ANO, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS QUANTIDADE_TOTAL
			FROM NOTAS_FISCAIS INNER JOIN ITENS_NOTAS_FISCAIS ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO
				GROUP BY NOTAS_FISCAIS.CPF, CONVERT(VARCHAR(7), NOTAS_FISCAIS.DATA_VENDA, 120)) TOTAL_VENDA ON TOTAL_VENDA.CPF = TABELA_DE_CLIENTES.CPF
					WHERE (TOTAL_VENDA.MES_ANO = '2015-01') AND (TABELA_DE_CLIENTES.VOLUME_DE_COMPRA < TOTAL_VENDA.QUANTIDADE_TOTAL)




