/*Desafio: vendas percentuais por tamanho*/
SELECT 
VENDA_TAMANHO.TAMANHO, VENDA_TAMANHO.ANO, VENDA_TAMANHO.VENDA_ANO, VENDA_ANO.VENDAS_TOTAL_ANO,
ROUND((CONVERT( FLOAT , VENDA_TAMANHO.VENDA_ANO) / CONVERT( FLOAT , VENDA_ANO.VENDAS_TOTAL_ANO)) * 100 ,2) AS PERCENTUAL
FROM 
(
SELECT  TABELA_DE_PRODUTOS.TAMANHO, YEAR(NOTAS_FISCAIS.DATA_VENDA) AS ANO, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS VENDA_ANO
FROM TABELA_DE_PRODUTOS 
INNER JOIN ITENS_NOTAS_FISCAIS 
ON TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO = ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO 
INNER JOIN NOTAS_FISCAIS 
ON ITENS_NOTAS_FISCAIS.NUMERO = NOTAS_FISCAIS.NUMERO
WHERE (YEAR(NOTAS_FISCAIS.DATA_VENDA)) = 2015
GROUP BY TABELA_DE_PRODUTOS.TAMANHO, YEAR(NOTAS_FISCAIS.DATA_VENDA)
) VENDA_TAMANHO
INNER JOIN
(
SELECT YEAR(NOTAS_FISCAIS.DATA_VENDA) AS ANO, 
SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS VENDAS_TOTAL_ANO
FROM NOTAS_FISCAIS
INNER JOIN ITENS_NOTAS_FISCAIS 
ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO
WHERE (YEAR(NOTAS_FISCAIS.DATA_VENDA) = 2015)
GROUP BY YEAR(NOTAS_FISCAIS.DATA_VENDA)
) VENDA_ANO
ON VENDA_TAMANHO.ANO = VENDA_ANO.ANO
ORDER BY VENDA_TAMANHO.VENDA_ANO DESC
				