/*Desafio: data por extenso*/
SELECT NOME, DATENAME(DAY, DATA_DE_NASCIMENTO) AS DIA, DATENAME(WEEKDAY, DATA_DE_NASCIMENTO) AS [DIA SEMANA], DATENAME(MONTH, DATA_DE_NASCIMENTO) AS MÊS, DATENAME(YEAR, DATA_DE_NASCIMENTO) AS ANO 
FROM TABELA_DE_CLIENTES