/*Desafio: formato do faturamento*/
SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
	FROM NOTAS_FISCAIS INNER JOIN ITENS_NOTAS_FISCAIS ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO
		WHERE YEAR(DATA_VENDA) = 2016
			GROUP BY YEAR(DATA_VENDA);