/*Desafio: listando expressão natural*/
SELECT 'O cliente ' + TABELA_DE_CLIENTES.NOME + ' comprou R$ ' + TRIM(STR(SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE * ITENS_NOTAS_FISCAIS.PRECO) ,10,2)) + ' no ano de ' + DATENAME(YEAR, NOTAS_FISCAIS.DATA_VENDA)
	FROM NOTAS_FISCAIS INNER JOIN ITENS_NOTAS_FISCAIS ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO INNER JOIN TABELA_DE_CLIENTES ON NOTAS_FISCAIS.CPF = TABELA_DE_CLIENTES.CPF
		WHERE YEAR(NOTAS_FISCAIS.DATA_VENDA) = '2016'
			GROUP BY TABELA_DE_CLIENTES.NOME, NOTAS_FISCAIS.DATA_VENDA;