/*Desafio: buscando os sabores dos produtos mais vendidos*/
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN (
	SELECT ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS INNER JOIN TABELA_DE_PRODUTOS ON ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
		GROUP BY ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO HAVING SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) > 394000 );