/*Desafio: nome dos produtos*/
SELECT ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS QUANTIDADE 
	FROM ITENS_NOTAS_FISCAIS INNER JOIN TABELA_DE_PRODUTOS ON ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
		GROUP BY ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO HAVING SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) > 394000 
			ORDER BY SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) DESC;

