/*Desafio: transformando HAVING em Subconsultas*/
SELECT SC.CODIGO_DO_PRODUTO, SC.NOME_DO_PRODUTO, SC.QUANTIDADE_TOTAL FROM
	(SELECT ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS QUANTIDADE_TOTAL 
		FROM ITENS_NOTAS_FISCAIS INNER JOIN TABELA_DE_PRODUTOS ON ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
			GROUP BY ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO) SC
				WHERE SC.QUANTIDADE_TOTAL > 394000 
					ORDER BY SC.QUANTIDADE_TOTAL DESC;