/*Desafio: usando visão para substituir o HAVING*/

/*CRIANDO A VIEW*/
CREATE VIEW xVIEW_QUANTIDADE_PRODUTOS AS 
	SELECT  ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS QUANTIDADE_TOTAL 
		FROM ITENS_NOTAS_FISCAIS INNER JOIN TABELA_DE_PRODUTOS ON ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
			GROUP BY ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO;

/*CONSULTA COM A VIEW*/
SELECT * FROM xVIEW_QUANTIDADE_PRODUTOS WHERE QUANTIDADE_TOTAL > 394000 ORDER BY QUANTIDADE_TOTAL DESC;